"""add ondelete cascade to foreign keys

Revision ID: e930bb2291d0
Revises: 268a2c008c35
Create Date: 2026-08-29 23:33:13.239134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e930bb2291d0'
down_revision: Union[str, None] = '268a2c008c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chat_sessions_user_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('experiments_user_id_fkey', 'experiments', type_='foreignkey')
    op.create_foreign_key(None, 'experiments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('kb_chunks_document_id_fkey', 'kb_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'kb_chunks', 'kb_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ml_runs_user_id_fkey', 'ml_runs', type_='foreignkey')
    op.drop_constraint('ml_runs_experiment_id_fkey', 'ml_runs', type_='foreignkey')
    op.create_foreign_key(None, 'ml_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ml_runs', 'experiments', ['experiment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ml_runs', type_='foreignkey')
    op.drop_constraint(None, 'ml_runs', type_='foreignkey')
    op.create_foreign_key('ml_runs_experiment_id_fkey', 'ml_runs', 'experiments', ['experiment_id'], ['id'])
    op.create_foreign_key('ml_runs_user_id_fkey', 'ml_runs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'kb_chunks', type_='foreignkey')
    op.create_foreign_key('kb_chunks_document_id_fkey', 'kb_chunks', 'kb_documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.create_foreign_key('experiments_user_id_fkey', 'experiments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_user_id_fkey', 'chat_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
